resources:
- pvc-0.yaml
- pod-0.yaml
- pvc-1.yaml
- pod-1.yaml
- pvc-2.yaml
- pod-2.yaml
- pvc-3.yaml
- pod-3.yaml
- pvc-4.yaml
- pod-4.yaml
- pvc-5.yaml
- pod-5.yaml
- pvc-6.yaml
- pod-6.yaml
- pvc-7.yaml
- pod-7.yaml
- pvc-8.yaml
- pod-8.yaml
- pvc-9.yaml
- pod-9.yaml
- pvc-10.yaml
- pod-10.yaml
- pvc-11.yaml
- pod-11.yaml
- pvc-12.yaml
- pod-12.yaml
- pvc-13.yaml
- pod-13.yaml
- pvc-14.yaml
- pod-14.yaml
- pvc-15.yaml
- pod-15.yaml
- pvc-16.yaml
- pod-16.yaml
- pvc-17.yaml
- pod-17.yaml
- pvc-18.yaml
- pod-18.yaml
- pvc-19.yaml
- pod-19.yaml
- pvc-20.yaml
- pod-20.yaml
- pvc-21.yaml
- pod-21.yaml
- pvc-22.yaml
- pod-22.yaml
- pvc-23.yaml
- pod-23.yaml
- pvc-24.yaml
- pod-24.yaml
- pvc-25.yaml
- pod-25.yaml
- pvc-26.yaml
- pod-26.yaml
- pvc-27.yaml
- pod-27.yaml
- pvc-28.yaml
- pod-28.yaml
- pvc-29.yaml
- pod-29.yaml
- pvc-0.yaml
- pod-0.yaml
- pvc-1.yaml
- pod-1.yaml
- pvc-2.yaml
- pod-2.yaml
- pvc-3.yaml
- pod-3.yaml
- pvc-4.yaml
- pod-4.yaml
- pvc-5.yaml
- pod-5.yaml
- pvc-6.yaml
- pod-6.yaml
- pvc-7.yaml
- pod-7.yaml
- pvc-8.yaml
- pod-8.yaml
- pvc-9.yaml
- pod-9.yaml
