apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sunil-07_1665393585-8-pvc
  namespace: sunil-07_1665393585
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: ocs-external-storagecluster-ceph-rbd
  volumeMode: Filesystem
