apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sunil-07_1665396122-2Gi-2-pvc
  namespace: sunil-07_1665396122
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: ocs-external-storagecluster-ceph-rbd
  volumeMode: Filesystem
