apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rahul-00-1675766753-2gi-3-pvc
  namespace: rahul-00-1675766753
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: ocs-external-storagecluster-ceph-rbd
  volumeMode: Filesystem
