apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rahul-01-1675766966-2gi-0-pvc
  namespace: rahul-01-1675766966
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: ocs-external-storagecluster-ceph-rbd
  volumeMode: Filesystem
