apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rahul-01-1675766966-1gi-3-pvc
  namespace: rahul-01-1675766966
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: ocs-external-storagecluster-ceph-rbd
  volumeMode: Filesystem
