apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sunil-07_1665397238-2Gi-1-pvc
  namespace: sunil-07_1665397238
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: ocs-external-storagecluster-ceph-rbd
  volumeMode: Filesystem
