apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sunil-07_1665396699-1Gi-3-pvc
  namespace: sunil-07_1665396699
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: ocs-external-storagecluster-ceph-rbd
  volumeMode: Filesystem
