apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sunil-07-1665397586-1Gi-1-pvc
  namespace: sunil-07-1665397586
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: ocs-external-storagecluster-ceph-rbd
  volumeMode: Filesystem
