apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rahul-001-1675754235-2gi-1-pvc
  namespace: rahul-001-1675754235
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: ocs-external-storagecluster-ceph-rbd
  volumeMode: Filesystem
