apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rahul-002-1675754581-2gi-2-pvc
  namespace: rahul-002-1675754581
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: ocs-external-storagecluster-ceph-rbd
  volumeMode: Filesystem
