apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sunil-07-1665398534-1gi-0-pvc
  namespace: sunil-07-1665398534
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: ocs-external-storagecluster-ceph-rbd
  volumeMode: Filesystem
