apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sunil-07-1665398534-2gi-2-pvc
  namespace: sunil-07-1665398534
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: ocs-external-storagecluster-ceph-rbd
  volumeMode: Filesystem
