apiVersion: v1
kind: Pod
metadata:
  name: sunil-00-1665495497-2gi-2-pod
  namespace: sunil-00-1665495497
spec:
  containers:
  - command:
    - sh
    - -c
    - while true; do echo $(date); dd if=/dev/urandom bs=1024 count=10240 of=/mnt/test/mbr.img
      oflag=append conv=notrunc; sync; sleep 1; done
    image: quay.io/vcppds7878/busybox:latest
    imagePullPolicy: IfNotPresent
    name: busybox
    volumeMounts:
    - mountPath: /mnt/test
      name: sunil-00-1665495497-2gi-2-volume
  volumes:
  - name: sunil-00-1665495497-2gi-2-volume
    persistentVolumeClaim:
      claimName: sunil-00-1665495497-2gi-2-pvc
      readOnly: false
