apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sunil-00-1665495497-1gi-4-pvc
  namespace: sunil-00-1665495497
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: ocs-external-storagecluster-ceph-rbd
  volumeMode: Filesystem
