apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sunil-00-1665496129-1gi-3-pvc
  namespace: sunil-00-1665496129
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: ocs-external-storagecluster-ceph-rbd
  volumeMode: Filesystem
