apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rahul-007-1675744417-2gi-2-pvc
  namespace: rahul-007-1675744417
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: ocs-external-storagecluster-ceph-rbd
  volumeMode: Filesystem
