apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sunil-00-1665497891-2gi-1-pvc
  namespace: sunil-00-1665497891
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: ocs-external-storagecluster-ceph-rbd
  volumeMode: Filesystem
