apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sunil-00-1665495337-1gi-1-pvc
  namespace: sunil-00-1665495337
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: ocs-external-storagecluster-ceph-rbd
  volumeMode: Filesystem
